import React from "react"
import { Link, graphql, useStaticQuery } from "gatsby"
import { Container, Row, Col } from '~paragon-react';


// MDX transforms markdown generated by gatsby-transformer-react-docgen
// This query filters out all of those markdown nodes and assumes all others
// are for page creation purposes.
const menuQuery = graphql`
query menuQuery {
  components: allMdx(
    filter: {parent: {internal: {owner: {nin: "gatsby-transformer-react-docgen"}}}, frontmatter: {type: {}}}
    sort: {fields: frontmatter___title}
  ) {
    categories: group(field: frontmatter___categories) {
      nodes {
        ...ComponentPage
      }
      fieldValue
    }
    types: group(field: frontmatter___type) {
      nodes {
        ...ComponentPage
      }
      fieldValue
    }
    all: nodes {
      ...ComponentPage
    }
  }
}

fragment ComponentPage on Mdx {
  id
  frontmatter {
    categories
    type
    title
  }
  fields {
    slug
  }
}
`


const ComponentNavItem = ({ id, fields, frontmatter }) => (
  <li key={id}>
    <Link to={fields.slug}>
      {frontmatter.title}
    </Link>
  </li>
);

const Menu = () => {
  const { components } = useStaticQuery(menuQuery);
  const { categories, types, all } = components;

  return (
    <Container>
      <h1>Components</h1>
      <Row>
        {categories.map(({ fieldValue, nodes }) => (
          <Col className="mb-5" sm={3}>
            <h4>{fieldValue}</h4>
            <ul className="list-unstyled">
              {nodes.map(ComponentNavItem)}
            </ul>
          </Col>
        ))}
      </Row>
      <hr />
      {types.map(({ fieldValue, nodes }) => (
          <Col>
            {fieldValue}
            {nodes.map(ComponentNavItem)}
          </Col>
        ))}
      <ul>
        {all.map(ComponentNavItem)}
      </ul>
    </Container>
  )
}

export default Menu
