# This file records information about this repo. Its use is described in OEP-55:
# https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'Paragon'
  description: "The design system and React component library for Open edX"
  links:
    - url: "https://paragon-openedx.netlify.app"
      title: "Documentation Website"
      # Backstage uses the MaterialUI Icon Set.
      # https://mui.com/material-ui/material-icons/
      # The value will be the name of the icon.
      icon: "Web"
  annotations:
    # (Optional) Annotation keys and values can be whatever you want.
    # We use it in Open edX repos to have a comma-separated list of GitHub user
    # names that might be interested in changes to the architecture of this
    # component.
    openedx.org/arch-interest-groups: "feanil"
spec:
  owner: group:paragon-working-group
  type: 'library'
  lifecycle: 'production'
