[context.production]
  environment = { NODE_VERSION = "16.15.1" }
[context.deploy-preview]
  environment = { SEGMENT_KEY = "", NODE_VERSION = "16.15.1" }
[functions]
  directory = "www/netlify/functions"
