[context.production]
  environment = { NODE_VERSION = "18.16.0" }
[context.deploy-preview]
  environment = { SEGMENT_KEY = "", NODE_VERSION = "18.16.0" }
[functions]
  directory = "www/netlify/functions"
