import React from "react"
import { Link, graphql } from "gatsby"

const BlogIndex = ({ data }) => {
  const { edges: components } = data.allMdx

  return (
    <div>
      <h1>Components</h1>

      <ul>
        {components.map(({ node: component }) => (
          <li key={component.id}>
            <Link to={component.fields.slug}>
              <h2>{component.frontmatter.title}</h2>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  )
}

// MDX transforms markdown generated by gatsby-transformer-react-docgen
// This query filters out all of those markdown nodes and assumes all others
// are for page creation purposes.
export const pageQuery = graphql`
  query blogIndex {
    allMdx(filter: {
      parent: {
        internal: {
          owner: {nin: "gatsby-transformer-react-docgen"}
        }
      }
    }) {
      edges {
        node {
          id
          frontmatter {
            title
          }
          fields {
            slug
          }
        }
      }
    }
  }
`

export default BlogIndex
