import React from "react"
import PropTypes from "prop-types"
import { Link, graphql, useStaticQuery } from "gatsby"
import { Container, Row, Col } from "~paragon-react"

// MDX transforms markdown generated by gatsby-transformer-react-docgen
// This query filters out all of those markdown nodes and assumes all others
// are for page creation purposes.
const menuQuery = graphql`
  query menuQuery {
    components: allMdx(
      filter: {
        parent: {
          internal: { owner: { nin: "gatsby-transformer-react-docgen" } }
        }
        frontmatter: { type: {} }
      }
      sort: { fields: frontmatter___title }
    ) {
      categories: group(field: frontmatter___categories) {
        nodes {
          ...ComponentPage
        }
        fieldValue
      }
      types: group(field: frontmatter___type) {
        nodes {
          ...ComponentPage
        }
        fieldValue
      }
      all: nodes {
        ...ComponentPage
      }
    }
  }

  fragment ComponentPage on Mdx {
    id
    frontmatter {
      categories
      type
      title
    }
    fields {
      slug
    }
  }
`

const ComponentNavItem = ({ id, fields, frontmatter, ...props }) => (
  <li {...props}>
    <Link to={fields.slug}>{frontmatter.title}</Link>
  </li>
)

const MenuComponentList = ({ children }) => (
  <div className="menu-component-list">{children}</div>
)
const MenuComponentListCategory = ({ children, title }) => (
  <div className="menu-component-list-category">
    <h5>{title}</h5>
    {children}
  </div>
)

const Menu = () => {
  const { components } = useStaticQuery(menuQuery)
  const { categories, all } = components

  return (
    <Container size="xl" className="py-5">
      <Row className="mb-5">
        <Col sm={3}>
          <h3 className="mb-3">Guides</h3>
          <ul className="list-unstyled small mb-4">
            <li>
              <Link to="/guides/installation-and-usage">
                Installation and usage
              </Link>
            </li>
            <li>
              <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://openedx.atlassian.net/wiki/spaces/BPL/pages/1773502564/Component+Contribution+Process"
              >
                Contributing components
              </a>
            </li>
            <li>
              <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://openedx.atlassian.net/wiki/spaces/BPL/overview"
              >
                Design documentation
              </a>
            </li>
            <li>
              <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-2021"
              >
                Paragon Figma library
              </a>
            </li>
          </ul>
          <h3 className="mb-3">Foundations</h3>
          <ul className="list-unstyled small mb-4">
            <li>
              <Link to="/foundations/colors">Colors</Link>
            </li>
            <li>
              <Link to="/foundations/typography">Typography</Link>
            </li>
            <li>
              <Link to="/foundations/layout">Layout</Link>
            </li>
            <li>
              <Link to="/foundations/spacing">Spacing</Link>
            </li>
            <li>
              <Link to="/foundations/icons">Icons</Link>
            </li>
            <li>
              <Link to="/foundations/css-utilities">CSS Utility Classes</Link>
            </li>
          </ul>
        </Col>
        <Col sm={9}>
          <h3 className="mb-3">Components</h3>
          <MenuComponentList>
            {categories.map(({ fieldValue, nodes }) => (
              <MenuComponentListCategory key={fieldValue} title={fieldValue}>
                <ul className="list-unstyled small mb-4">
                  {nodes
                    .map(node => ({ key: node.id, ...node }))
                    .map(ComponentNavItem)}
                </ul>
              </MenuComponentListCategory>
            ))}
          </MenuComponentList>
        </Col>
      </Row>
      <div className="menu-all-components">
        <h3 className="mb-3">All components (A-Z)</h3>
        <MenuComponentList>
          <ul className="list-unstyled small mb-4">
            {all.map(node => ({ key: node.id, ...node })).map(ComponentNavItem)}
          </ul>
        </MenuComponentList>
      </div>
    </Container>
  )
}

export default Menu
