import {
  useLayoutEffect, useMemo, useRef, useState,
  type CSSProperties,
} from 'react';

import { Button } from '../Button';
import styles from './themeVariables.module.css';

/**
 * The Button module's theme variables, grouped for readability.
 *
 * This is the same `--pgn-*` custom-property set the current Paragon docs list
 * under "Theme Variables" for Button — there, the list is scraped from the
 * component's SCSS (every `var(--pgn-…)` reference) and rendered read-only with
 * its computed value (see www/src/components/ComponentVariablesTable.tsx). Here
 * the identical set is authored explicitly (the prototype has no SCSS to scrape)
 * and made editable, so changing a token updates the live preview below.
 */
interface VarGroup {
  label: string;
  variables: string[];
}

export const BUTTON_THEME_VARIABLES: VarGroup[] = [
  {
    label: 'Sizing',
    variables: [
      '--pgn-size-btn-border-width',
      '--pgn-size-btn-border-radius-base',
      '--pgn-size-btn-border-radius-sm',
      '--pgn-size-btn-border-radius-lg',
      '--pgn-size-btn-focus-width',
      '--pgn-size-btn-focus-border-radius-base',
      '--pgn-size-btn-focus-border-radius-sm',
      '--pgn-size-btn-focus-border-radius-lg',
    ],
  },
  {
    label: 'Spacing',
    variables: [
      '--pgn-spacing-btn-padding-y-base',
      '--pgn-spacing-btn-padding-x-base',
      '--pgn-spacing-btn-padding-y-sm',
      '--pgn-spacing-btn-padding-x-sm',
      '--pgn-spacing-btn-padding-y-lg',
      '--pgn-spacing-btn-padding-x-lg',
      '--pgn-spacing-btn-block-spacing-y',
      '--pgn-spacing-btn-focus-distance-to-border',
    ],
  },
  {
    label: 'Typography',
    variables: [
      '--pgn-typography-btn-font-family',
      '--pgn-typography-btn-font-weight',
      '--pgn-typography-btn-font-size-base',
      '--pgn-typography-btn-font-size-sm',
      '--pgn-typography-btn-font-size-lg',
      '--pgn-typography-btn-line-height-base',
      '--pgn-typography-btn-line-height-sm',
      '--pgn-typography-btn-line-height-lg',
    ],
  },
  {
    label: 'Base colors',
    variables: [
      '--pgn-color-body-base',
      '--pgn-color-link-base',
      '--pgn-color-link-hover',
    ],
  },
  // Per-variant colours. The upstream docs' "Theme variables" table omits these:
  // it is generated by scraping `var(--pgn-…)` out of Button's SCSS, but there
  // each variant's tokens are written with interpolation
  // (`--pgn-color-btn-bg-#{$variant}`), which the scraper's regex never matches.
  // They are the tokens that actually colour each variant, so they are listed
  // here. Note: editing the *generic* `--pgn-btn-bg` would not work — every
  // `.btn-<variant>` re-declares it locally from the source tokens below, so the
  // source token is what has to be overridden.
  {
    label: 'Brand variant colors',
    variables: [
      '--pgn-color-btn-bg-brand',
      '--pgn-color-btn-text-brand',
      '--pgn-color-btn-border-brand',
    ],
  },
  {
    label: 'Primary variant colors',
    variables: [
      '--pgn-color-btn-bg-primary',
      '--pgn-color-btn-text-primary',
      '--pgn-color-btn-border-primary',
    ],
  },
  {
    label: 'Secondary variant colors',
    variables: [
      '--pgn-color-btn-bg-secondary',
      '--pgn-color-btn-text-secondary',
      '--pgn-color-btn-border-secondary',
    ],
  },
  {
    label: 'Tertiary variant colors',
    variables: [
      '--pgn-color-btn-bg-tertiary',
      '--pgn-color-btn-text-tertiary',
      '--pgn-color-btn-border-tertiary',
    ],
  },
  {
    label: 'Success variant colors',
    variables: [
      '--pgn-color-btn-bg-success',
      '--pgn-color-btn-text-success',
      '--pgn-color-btn-border-success',
    ],
  },
  {
    label: 'Danger variant colors',
    variables: [
      '--pgn-color-btn-bg-danger',
      '--pgn-color-btn-text-danger',
      '--pgn-color-btn-border-danger',
    ],
  },
  {
    label: 'Other',
    variables: [
      '--pgn-transition-btn',
      '--pgn-other-btn-disabled-opacity',
      '--pgn-typography-link-decoration-base',
      '--pgn-typography-link-decoration-hover',
    ],
  },
];

const ALL_VARIABLES = BUTTON_THEME_VARIABLES.flatMap((g) => g.variables);

/**
 * True when a value looks like a colour we can offer a native colour picker for.
 * Covers #rgb, #rgba, #rrggbb, #rrggbbaa and rgb()/rgba() — the forms the
 * compiled Paragon colour tokens resolve to.
 */
function isColorValue(value: string): boolean {
  const v = value.trim();
  return /^#([0-9a-f]{3,4}|[0-9a-f]{6}|[0-9a-f]{8})$/i.test(v) || /^rgba?\(/i.test(v);
}

/**
 * Normalises any CSS colour to the `#rrggbb` a native `<input type="color">`
 * needs. Alpha (from #rgba / #rrggbbaa / rgba()) is dropped for the swatch — the
 * adjacent text field keeps the full, alpha-preserving value.
 */
function toHex(value: string): string {
  const v = value.trim();
  const expand = (c: string) => c + c;
  if (/^#[0-9a-f]{6}([0-9a-f]{2})?$/i.test(v)) return v.slice(0, 7);
  if (/^#[0-9a-f]{3,4}$/i.test(v)) {
    return `#${v.slice(1, 4).split('').map(expand).join('')}`;
  }
  const m = v.match(/rgba?\(\s*(\d+)[\s,]+(\d+)[\s,]+(\d+)/i);
  if (m) {
    const hex = m.slice(1, 4).map((n) => Number(n).toString(16).padStart(2, '0')).join('');
    return `#${hex}`;
  }
  return '#000000';
}

/**
 * An interactive version of Paragon's "Theme Variables" docs table for Button.
 *
 * Reads the initial (computed) value of every Button `--pgn-*` token from the
 * live preview container, lists them in an editable table, and writes any edit
 * back onto that container as a custom-property override. Because `.btn` styling
 * is authored entirely over these tokens, the preview buttons re-render with the
 * new value instantly — the same mechanism `@edx/brand` uses to theme Paragon.
 */
export function ThemeVariables() {
  const previewRef = useRef<HTMLDivElement>(null);
  // Computed token defaults, read once from the DOM after mount.
  const [defaults, setDefaults] = useState<Record<string, string>>({});
  // Only the tokens the user has actually edited (so "Reset" can restore them).
  const [overrides, setOverrides] = useState<Record<string, string>>({});

  useLayoutEffect(() => {
    if (!previewRef.current) return;
    const computed = getComputedStyle(previewRef.current);
    const initial: Record<string, string> = {};
    for (const name of ALL_VARIABLES) {
      initial[name] = computed.getPropertyValue(name).trim();
    }
    setDefaults(initial);
  }, []);

  // The custom-property overrides applied to the preview container.
  const previewStyle = useMemo(
    () => overrides as unknown as CSSProperties,
    [overrides],
  );

  const hasOverrides = Object.keys(overrides).length > 0;

  const setValue = (name: string, value: string) => {
    setOverrides((prev) => ({ ...prev, [name]: value }));
  };

  const resetValue = (name: string) => {
    setOverrides((prev) => {
      const next = { ...prev };
      delete next[name];
      return next;
    });
  };

  const valueOf = (name: string) => overrides[name] ?? defaults[name] ?? '';

  return (
    <div className={styles.root}>
      {/* Live preview: the element the edited tokens are applied to. */}
      <div ref={previewRef} className={styles.preview} style={previewStyle}>
        <div className={styles.previewRow}>
          <Button variant="brand">Brand</Button>
          <Button variant="primary">Primary</Button>
          <Button variant="outline-primary">Outline Primary</Button>
          <Button variant="secondary">Secondary</Button>
          <Button variant="tertiary">Tertiary</Button>
          <Button variant="link">Link</Button>
        </div>
        <div className={styles.previewRow}>
          <Button variant="primary" size="sm">Small</Button>
          <Button variant="primary">Medium</Button>
          <Button variant="primary" size="lg">Large</Button>
        </div>
        <div className={styles.previewRow}>
          <Button variant="success">Success</Button>
          <Button variant="danger">Danger</Button>
          <Button variant="primary" disabled>Disabled</Button>
        </div>
      </div>

      <div className={styles.toolbar}>
        <span className={styles.toolbarLabel}>
          Edit a token to see it applied to the buttons above
        </span>
        <button
          type="button"
          className={styles.resetAll}
          onClick={() => setOverrides({})}
          disabled={!hasOverrides}
        >
          Reset all
        </button>
      </div>

      <div className={styles.tableWrap}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th scope="col">CSS Variable</th>
              <th scope="col">Value</th>
              <th scope="col" aria-label="Reset" />
            </tr>
          </thead>
          <tbody>
            {BUTTON_THEME_VARIABLES.map((group) => [
              <tr key={group.label} className={styles.groupRow}>
                <td colSpan={3}><span className={styles.groupLabel}>{group.label}</span></td>
              </tr>,
              ...group.variables.map((name) => {
                const value = valueOf(name);
                const overridden = name in overrides;
                return (
                  <tr key={name} className={overridden ? styles.overridden : undefined}>
                    <td><code className={styles.varName}>{name}</code></td>
                    <td>
                      <div className={styles.valueCell}>
                        {isColorValue(value) && (
                          <input
                            type="color"
                            className={styles.swatch}
                            aria-label={`${name} colour`}
                            value={toHex(value)}
                            onChange={(e) => setValue(name, e.target.value)}
                          />
                        )}
                        <input
                          type="text"
                          className={styles.valueInput}
                          aria-label={name}
                          value={value}
                          spellCheck={false}
                          onChange={(e) => setValue(name, e.target.value)}
                        />
                      </div>
                    </td>
                    <td>
                      <button
                        type="button"
                        className={styles.resetRow}
                        aria-label={`Reset ${name}`}
                        title="Reset to default"
                        onClick={() => resetValue(name)}
                      >
                        ↺
                      </button>
                    </td>
                  </tr>
                );
              }),
            ])}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default ThemeVariables;
