name: Node.js CI

on:
  pull_request:
    branches:
    - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
    - name: Setup Nodejs
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version-file: '.nvmrc'
    - name: Install dependencies
      run: npm ci
    - name: Check Types
      run: npm run type-check
    - name: Lint
      run: make lint
    - name: Test
      run: npm run test
    - name: Verify icon changes
      run: |
        cd icons
        rm -rf jsx
        rm -rf es5
        npm run build
        if [[ -n $(git status -s) ]]; then
          echo "::error::Generated icons do not match committed icons. Please run \`npm run build\` in the icons directory."
          exit 1
        fi
    - name: Build
      run: npm run build
    - name: Build Docs
      run: make build-docs
    - name: Coverage
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
