# Run commitlint on the commit messages in a pull request.

name: Lint Commit Messages

on:
  pull_request:
    branches-ignore:
      - 'automation/sync-alpha-master'

jobs:
  commitlint:
    uses: openedx/.github/.github/workflows/commitlint.yml@master
