name: Manual Publish
on: [workflow_dispatch]
jobs:
  release:
    name: Manual Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0
    - name: Setup Nodejs Env
      run: echo "NODE_VER=`cat .nvmrc`" >> $GITHUB_ENV
    - name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: ${{ env.NODE_VER }}
    - name: Install dependencies
      run: npm ci
    - name: Validate package-lock.json changes
      run: make validate-no-uncommitted-package-lock-changes
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test
    - name: i18n_extract
      run: npm run i18n_extract
    - name: Coverage
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Build
      run: npm run build
    # NPM expects to be authenticated for publishing. This step will fail CI if NPM is not authenticated
    - name: Check NPM authentication
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}" >> .npmrc
        npm whoami
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}
      # `npm publish` relies on version specified in package.json file
      run: npm publish --tag old-version
