name: Sync alpha with master
on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Git User
        uses: fregante/setup-git-user@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Sync changes
        run: |
          git switch alpha
          git pull origin alpha
          git rebase master
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.requirements_bot_github_token }}
          branch: automation/sync-alpha-master
          title: "chore(release): sync from master to alpha"
          body: "Sync changes from `master` to `alpha`."
      - name: Enable Pull Request Auto Merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.requirements_bot_github_token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
