name: Sync alpha with master
on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Sync alpha with master
        uses: connor-baer/action-sync-branch@main
        with:
          branch: alpha
          token: ${{ secrets.requirements_bot_github_token }}
          force: false
